### ISSUE TITLE
.pyc files not excluded with .gitignore

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible/ansible-container-demo#1]
There are redundant python files due to the project settings.

**Comment by chouseknecht** [comment]
@bbaassssiiee, thanks for the suggestion. I updated the .gitignore in [ansible/django-gulp-nginx](https://github.com/ansible/django-gulp-nginx/blob/master/.gitignore). If you follow the readme, it instructions you to `init` your local project directory with that project, which is the source of the .gitignore.
