### ISSUE TITLE
Unable to build containers

### ISSUE THREAD

**Issue by mixpix3ls** [ansible/ansible-container-demo#3]
Executing `ansible-container build` produces the following error:

`ERROR	No Ansible Container project data found - do you need to run "ansible-container init"?`

This is after having executed the init command in the README:

`ansible-container init ansible.django-gulp-nginx`

**Comment by giannisalinetti** [comment]
Same issue for me. 
I also followed the documentation here https://docs.ansible.com/ansible-container/getting_started.html

**Comment by nathanielks** [comment]
@chouseknecht bumping. I would _love_ to be able to evaluate `ansible-container`, but the demo isn't working. That's a bit of a deal breaker!

**Comment by chouseknecht** [comment]
@mixpix3ls 
@giannisalinetti 
@nathanielks 

Thanks for your interest in Ansible Container. Apologies that it's taken until now to get the demo working. But here it is. It's finally working once again. 

It's updated to work with the 0.9 release. If you intend to run through the actual steps, I recommend running Ansible Container from source, as opposed to installing it from PyPi. As I was repairing the demo, I fixed a few bugs in Ansible Container, and the fixes are only available in the development branch.

**Comment by nathanielks** [comment]
Much obliged, @chouseknecht!
